import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidebarWrapper from "./components/SidebarWrapper";
import { SidebarProvider } from "@/context/SidebarContext";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dashboard | Sazin Group",
  description: "Generated by X Team",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          {/* <Navbar /> */}
          <div className="h-[calc(100vh-64px)] overflow-auto flex items-start justify-center">
            {/* Sidebar সবসময় থাকবে */}
            <div className="w-[20%] min-w-[280px] h-full shadow-lg">
              <SidebarWrapper />
            </div>
            {/* <main className="flex-1 rounded-br-md overflow-auto h-full p-4 bg-gray-50">{children}</main> */}
            {/* //update code  */}
            <main className="flex-1 rounded-br-md overflow-auto h-full p-4 bg-gray-100">
              {/* Top Navbar */}
              <div className="mb-4">
                <Navbar />
              </div>

              {/* Main Content */}
              <div className="">{children}</div>
            </main>


          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
