import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/context/SidebarContext";
import Providers from "@/utils/QueryProvider";
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dashboard | Sazin Group",
  description: "Generated by X Team",
    icons: {
    icon: "/favicon.png", // ✅ favicon path
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
      >
      <Toaster position="top-right" reverseOrder={false} />
        <Providers>
          <SidebarProvider>
             {children}
        </SidebarProvider>
      </Providers>
      </body>
    </html>
  );
}