import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidebarWrapper from "./components/SidebarWrapper";
import { SidebarProvider } from "@/context/SidebarContext";
import Navbar from "@/components/Navbar";
import Providers from "@/utils/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dashboard | Sazin Group",
  description: "Generated by X Team",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <SidebarProvider>
           <div className="h-[100vh] overflow-auto flex items-start justify-center">
                <div className="h-[100vh] w-full overflow-auto flex items-start justify-center">
                  {/* Sidebar সবসময় থাকবে */}
                    <div className="w-[20%] min-w-[280px] h-full shadow-lg">

                      <SidebarWrapper />
                    </div>
                    {/* <main className="flex-1 rounded-br-md overflow-auto h-full p-4 bg-gray-50">{children}</main> */}
                    {/* //update code  */}
                    <main className="flex-1 rounded-br-md overflow-auto h-full bg-gray-100">
                      {/* Top Navbar */}
                        <Navbar />

                      {/* Main Content */}
                      <div className=" p-4">
                        {children}
                      </div>
                    </main>
              </div>
            </div>
        </SidebarProvider>
      </Providers>
      </body>
    </html>
  );
}