// data.js

export const productsData = [
        {
          id: 1,
          category: "full-face",
          title: "Full Face Helmet",
          productName: "RiderX Full Shield",
          shortDescription: "Durable full face helmet with scratch-resistant visor",
          price: 120,
          image: "/images/full-face-helmet1.jpg",
          isFeatured: true,
        },
        {
          id: 2,
          category: "full-face",
          title: "Full Face Helmet",
          productName: "StormGuard Pro",
          shortDescription: "High-impact resistance, lightweight full face helmet",
          price: 150,
          image: "/images/full-face-helmet2.jpg",
          isFeatured: false,
        },
        {
            id: 3,
            category: "full-face",
            title: "Full Face Helmet",
            productName: "AeroShield Full Face",
            shortDescription: "Aerodynamic design for high-speed rides",
            price: 200,
            image: "/images/full-face-helmet3.jpg",
            isFeatured: false,
        },
        {
          id: 4,
          category: "full-face",
          title: "Full Face Helmet",
          productName: "RiderX Full Shield",
          shortDescription: "Durable full face helmet with scratch-resistant visor",
          price: 120,
          image: "/images/full-face-helmet1.jpg",
          isFeatured: true,
        },
        {
          id: 5,
          category: "full-face",
          title: "Full Face Helmet",
          productName: "StormGuard Pro",
          shortDescription: "High-impact resistance, lightweight full face helmet",
          price: 150,
          image: "/images/full-face-helmet2.jpg",
          isFeatured: false,
        },
        {
            id: 6,
            category: "full-face",
            title: "Full Face Helmet",
            productName: "AeroShield Full Face",
            shortDescription: "Aerodynamic design for high-speed rides",
            price: 200,
            image: "/images/full-face-helmet3.jpg",
            isFeatured: false,
        },
        {
            id: 7,
            category: "full-face",
            title: "Full Face Helmet",
            productName: "AeroShield Full Face",
            shortDescription: "Aerodynamic design for high-speed rides",
                price: 200,
                image: "/images/full-face-helmet3.jpg",
                isFeatured: false,
            },
            {
                id: 8,
                category: "full-face",
                title: "Full Face Helmet",
                productName: "AeroShield Full Face",
                shortDescription: "Aerodynamic design for high-speed rides",
                price: 200,
                image: "/images/full-face-helmet3.jpg",
                isFeatured: false,
            },
        {
          id: 9,
          category: "modular",
          title: "Modular Helmet",
          productName: "FlexiRide Modular",
          shortDescription: "Flip-up modular helmet with dual visor system",
          price: 180,
          image: "/images/modular-helmet1.jpg",
          isFeatured: true,
        },
        {
          id: 10,
          category: "modular",
          title: "Modular Helmet",
          productName: "FlexiRide Modular",
          shortDescription: "Flip-up modular helmet with dual visor system",
          price: 180,
          image: "/images/modular-helmet1.jpg",
          isFeatured: true,
        },
        {
          id: 11,
          category: "modular",
          title: "Modular Helmet",
          productName: "FlexiRide Modular",
          shortDescription: "Flip-up modular helmet with dual visor system",
          price: 180,
          image: "/images/modular-helmet1.jpg",
          isFeatured: true,
        },
        {
          id: 12,
          category: "modular",
          title: "Modular Helmet",
          productName: "FlexiRide Modular",
          shortDescription: "Flip-up modular helmet with dual visor system",
          price: 180,
          image: "/images/modular-helmet1.jpg",
          isFeatured: true,
        },
        {
          id: 13,
          category: "modular",
          title: "Modular Helmet",
          productName: "FlexiRide Modular",
          shortDescription: "Flip-up modular helmet with dual visor system",
          price: 180,
          image: "/images/modular-helmet1.jpg",
          isFeatured: true,
        },
        {
          id: 14,
          category: "modular",
          title: "Modular Helmet",
          productName: "FlexiRide Modular",
          shortDescription: "Flip-up modular helmet with dual visor system",
          price: 180,
          image: "/images/modular-helmet1.jpg",
          isFeatured: true,
        },
        {
          id: 15,
          category: "modular",
          title: "Modular Helmet",
          productName: "FlexiRide Modular",
          shortDescription: "Flip-up modular helmet with dual visor system",
          price: 180,
          image: "/images/modular-helmet1.jpg",
          isFeatured: true,
        },
        {
          id: 16,
          category: "modular",
          title: "Modular Helmet",
          productName: "FlexiRide Modular",
          shortDescription: "Flip-up modular helmet with dual visor system",
          price: 180,
          image: "/images/modular-helmet1.jpg",
          isFeatured: true,
        },
        {
          id: 17,
          category: "modular",
          title: "Modular Helmet",
          productName: "FlexiRide Modular",
          shortDescription: "Flip-up modular helmet with dual visor system",
          price: 180,
          image: "/images/modular-helmet1.jpg",
          isFeatured: true,
        },

        {
          id: 18,
          category: "open-face",
          title: "Open Face Helmet",
          productName: "Urban Breeze",
          shortDescription: "Comfortable open face helmet ideal for city rides",
          price: 90,
          image: "/images/open-face-helmet1.jpg",
          isFeatured: false,
        },
        {
          id: 19,
          category: "open-face",
          title: "Open Face Helmet",
          productName: "Urban Breeze",
          shortDescription: "Comfortable open face helmet ideal for city rides",
          price: 90,
          image: "/images/open-face-helmet1.jpg",
          isFeatured: false,
        },
        {
          id: 20,
          category: "open-face",
          title: "Open Face Helmet",
          productName: "Urban Breeze",
          shortDescription: "Comfortable open face helmet ideal for city rides",
          price: 90,
          image: "/images/open-face-helmet1.jpg",
          isFeatured: false,
        },
        {
          id: 21,
          category: "open-face",
          title: "Open Face Helmet",
          productName: "Urban Breeze",
          shortDescription: "Comfortable open face helmet ideal for city rides",
          price: 90,
          image: "/images/open-face-helmet1.jpg",
          isFeatured: false,
        },
        {
          id: 22,
          category: "open-face",
          title: "Open Face Helmet",
          productName: "Urban Breeze",
          shortDescription: "Comfortable open face helmet ideal for city rides",
          price: 90,
          image: "/images/open-face-helmet1.jpg",
          isFeatured: false,
        },
        {
          id: 23,
          category: "open-face",
          title: "Open Face Helmet",
          productName: "Urban Breeze",
          shortDescription: "Comfortable open face helmet ideal for city rides",
          price: 90,
          image: "/images/open-face-helmet1.jpg",
          isFeatured: false,
        },
        {
          id: 24,
          category: "open-face",
          title: "Open Face Helmet",
          productName: "Urban Breeze",
          shortDescription: "Comfortable open face helmet ideal for city rides",
          price: 90,
          image: "/images/open-face-helmet1.jpg",
          isFeatured: false,
        },
        {
          id: 25,
          category: "open-face",
          title: "Open Face Helmet",
          productName: "Urban Breeze",
          shortDescription: "Comfortable open face helmet ideal for city rides",
          price: 90,
          image: "/images/open-face-helmet1.jpg",
          isFeatured: false,
        },
        {
          id: 26,
          category: "half-face",
          title: "Half Face Helmet",
          productName: "Cruiser Half",
          shortDescription: "Lightweight half face helmet with minimal design",
          price: 70,
          image: "/images/half-face-helmet1.jpg",
          isFeatured: false,
        },

        {
          id: 27,
          category: "safety-helmets",
          title: "Safety Helmet",
          productName: "HardHat Pro",
          shortDescription: "Industrial safety helmet with strong impact protection",
          price: 25,
          image: "/images/safety-helmet1.jpg",
          isFeatured: true,
        },

        {
          id: 28,
          category: "safety-goggles",
          title: "Safety Goggles",
          productName: "ClearVision Pro",
          shortDescription: "Anti-fog safety goggles with UV protection",
          price: 15,
          image: "/images/safety-goggles1.jpg",
          isFeatured: false,
        },

        {
          id: 29,
          category: "hearing-protection",
          title: "Ear Protection",
          productName: "SoundShield Ear Muffs",
          shortDescription: "Noise reduction earmuffs for industrial use",
          price: 40,
          image: "/images/hearing-protection1.jpg",
          isFeatured: false,
        },

        {
          id: 30,
          category: "safety-gloves",
          title: "Safety Gloves",
          productName: "GripX Pro",
          shortDescription: "Cut-resistant industrial gloves with firm grip",
          price: 12,
          image: "/images/safety-gloves1.jpg",
          isFeatured: true,
        },

        {
          id: 31,
          category: "safety-shoes",
          title: "Safety Shoes",
          productName: "SteelToe Max",
          shortDescription: "Heavy-duty safety shoes with steel toe cap",
          price: 55,
          image: "/images/safety-shoes1.jpg",
          isFeatured: true,
        },

        {
          id: 32,
          category: "high-visibility-vests",
          title: "High-Visibility Vest",
          productName: "BrightGuard Vest",
          shortDescription: "Reflective vest for night safety",
          price: 18,
          image: "/images/hi-vis-vest1.jpg",
          isFeatured: false,
        },

        {
          id: 33,
          category: "respirators-masks",
          title: "Respirator Mask",
          productName: "AirSafe Pro",
          shortDescription: "Industrial grade respirator with filter",
          price: 35,
          image: "/images/respirator1.jpg",
          isFeatured: true,
        },
 
        {
          id: 34,
          category: "coveralls-protective-suits",
          title: "Protective Suit",
          productName: "SafeSuit Coverall",
          shortDescription: "Chemical-resistant protective suit",
          price: 60,
          image: "/images/protective-suit1.jpg",
          isFeatured: false,
        },

        {
          id: 35,
          category: "fall-protection-harness",
          title: "Safety Harness",
          productName: "FallGuard Harness",
          shortDescription: "Durable harness for fall protection",
          price: 85,
          image: "/images/safety-harness1.jpg",
          isFeatured: true,
        },

        {
          id: 36,
          category: "welding-helmets-gloves",
          title: "Welding Helmet",
          productName: "WeldShield Pro",
          shortDescription: "Auto-darkening welding helmet with gloves",
          price: 95,
          image: "/images/welding-helmet1.jpg",
          isFeatured: false,
        },

  {
    id: 1,
    category: "fruits",
    title: "Fruits",
    productName: "Fresh Fruits",
    shortDescription: "Seasonal fresh and organic fruits",
    price: 50,
    image: "/images/categories/fruits.jpg",
    isFeatured: true,
  },
  {
    id: 2,
    category: "vegetables",
    title: "Vegetables",
    productName: "Green Vegetables",
    shortDescription: "Organic and farm-fresh vegetables",
    price: 30,
    image: "/images/categories/vegetables.jpg",
    isFeatured: false,
  },
  {
    id: 3,
    category: "dairy",
    title: "Dairy",
    productName: "Dairy Products",
    shortDescription: "Milk, cheese, butter and more",
    price: 80,
    image: "/images/categories/dairy.jpg",
    isFeatured: true,
  },
  {
    id: 4,
    category: "meat",
    title: "Meat",
    productName: "Fresh Meat",
    shortDescription: "High quality fresh meat",
    price: 150,
    image: "/images/categories/meat.jpg",
    isFeatured: false,
  },
  {
    id: 5,
    category: "grains",
    title: "Grains",
    productName: "Organic Grains",
    shortDescription: "Rice, wheat and other grains",
    price: 40,
    image: "/images/categories/grains.jpg",
    isFeatured: false,
  },
  {
    id: 6,
    category: "seafood",
    title: "Seafood",
    productName: "Fresh Seafood",
    shortDescription: "Shrimps, crabs and more seafood",
    price: 200,
    image: "/images/categories/seafood.jpg",
    isFeatured: true,
  },
  {
    id: 7,
    category: "fish",
    title: "Fish",
    productName: "Fresh Fish",
    shortDescription: "Rohu, Katla, Hilsa and more fish",
    price: 120,
    image: "/images/categories/fish.jpg",
    isFeatured: true,
  },
  {
    id: 8,
    category: "fish-fry",
    title: "Fish Fry",
    productName: "Baby Fish (Fry)",
    shortDescription: "Fresh baby fish for farming",
    price: 70,
    image: "/images/categories/fish-fry.jpg",
    isFeatured: false,
  },
  {
    id: 9,
    category: "fish-eggs",
    title: "Fish Eggs (Roe)",
    productName: "Fish Eggs",
    shortDescription: "Fresh fish eggs for breeding",
    price: 90,
    image: "/images/categories/fish-eggs.jpg",
    isFeatured: false,
  },
];

